// src/screens/ProfileScreen.tsx
import React, { useState, useEffect } from 'react';
import { Alert, View, ScrollView, StyleSheet } from 'react-native';
import { Text, TextInput, Card, Checkbox, Button, Divider, Switch, ActivityIndicator } from 'react-native-paper';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { auth, db } from '../config/firebase';
import { doc, getDoc, collection, query, where, updateDoc, getDocs, orderBy, limit } from 'firebase/firestore';
import type { User, HeartsTransaction } from '../types';
import ReputationCard from '../components/ReputationCard';
import { getReputation, getReputationTips, triggerReputationCalculation } from '../lib/reputationHelpers';
import type { Reputation } from '../lib/reputationHelpers';

export default function ProfileScreen({ navigation }: any) {
  const insets = useSafeAreaInsets();
  const [user, setUser] = useState<User | null>(null);
  const [reputation, setReputation] = useState<Reputation | null>(null);
  const [recentTransactions, setRecentTransactions] = useState<HeartsTransaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingReputation, setLoadingReputation] = useState(true);
  const [refreshingReputation, setRefreshingReputation] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editName, setEditName] = useState('');
  const [editDisplayName, setEditDisplayName] = useState('');
  const [editPhone, setEditPhone] = useState('');
  const [saving, setSaving] = useState(false);
  const [useAutoGenerated, setUseAutoGenerated] = useState(false);
  const [exactDistance, setExactDistance] = useState(user?.privacy_settings?.exact_distance ?? false);

  useEffect(() => {
    loadProfile();
  }, []);

  async function loadProfile() {
    try {
      const currentUser = auth.currentUser;
      if (!currentUser) return;

      // Load user data
      const userDoc = await getDoc(doc(db, 'users', currentUser.uid));
      if (userDoc.exists()) {
        const userData = { id: userDoc.id, ...userDoc.data() } as User;
        setUser(userData);
        
        // Initialize edit values
        setEditName(userData.name || '');
        setEditDisplayName(userData.display_name || '');
        setEditPhone(userData.phone_number || '');
      }
      
      // Load recent transactions
      await loadRecentTransactions(currentUser.uid);

      // Load reputation
      await loadReputationData(currentUser.uid);

      setLoading(false);
    } catch (error) {
      console.error('Error loading profile:', error);
      setLoading(false);
    }
  }

  async function loadReputationData(userId: string) {
    setLoadingReputation(true);
    try {
      const rep = await getReputation(userId);
      setReputation(rep);
    } catch (error) {
      console.error('Error loading reputation:', error);
    } finally {
      setLoadingReputation(false);
    }
  }

  async function handleRefreshReputation() {
    const currentUser = auth.currentUser;
    if (!currentUser) return;
    
    setRefreshingReputation(true);
    try {
      const rep = await triggerReputationCalculation(currentUser.uid);
      setReputation(rep);
    } catch (error) {
      console.error('Error refreshing reputation:', error);
      alert('Kunde inte uppdatera reputation');
    } finally {
      setRefreshingReputation(false);
    }
  }

  async function handleSaveProfile() {
    // Validation
    if (!editName.trim()) {
      Alert.alert('Fel', 'Namn får inte vara tomt');
      return;
    }

    // Phone validation
    const phoneRegex = /^(\+46|0)[0-9]{9,10}$/;
    const cleanedPhone = editPhone.replace(/[\s-]/g, '');
    if (cleanedPhone && !phoneRegex.test(cleanedPhone)) {
      Alert.alert('Fel', 'Ogiltigt telefonnummer');
      return;
    }

    setSaving(true);
    try {
      const currentUser = auth.currentUser;
      if (!currentUser) return;

      // Determine display name based on checkbox
      let finalDisplayName;
      if (useAutoGenerated) {
        // Generate new random name
        finalDisplayName = `Granne #${Math.floor(1000 + Math.random() * 9000)}`;
      } else {
        // Use entered name, or keep existing, or generate if neither
        finalDisplayName = editDisplayName.trim() || 
          user?.display_name || 
          `Granne #${Math.floor(1000 + Math.random() * 9000)}`;
      }

      await updateDoc(doc(db, 'users', currentUser.uid), {
        name: editName.trim(),
        display_name: finalDisplayName,
        phone_number: cleanedPhone
      });

      // Reload profile
      await loadProfile();
      setEditMode(false);
      setUseAutoGenerated(false); // Reset checkbox
      
      Alert.alert('Sparat!', 'Din profil har uppdaterats.');
    } catch (error) {
      console.error('Error saving profile:', error);
      Alert.alert('Fel', 'Kunde inte spara profil');
    } finally {
      setSaving(false);
    }
  }

  function handleCancelEdit() {
    // Reset to current values
    setEditName(user?.name || '');
    setEditDisplayName(user?.display_name || '');
    setEditPhone(user?.phone_number || '');
    setUseAutoGenerated(false); // Reset checkbox
    setEditMode(false);
  }

  async function loadRecentTransactions(userId: string) {
    try {
      // Get recent sent transactions
      const sentQuery = query(
        collection(db, 'hearts_transactions'),
        where('from_user', '==', userId),
        orderBy('created_at', 'desc'),
        limit(3)
      );
      const sentSnapshot = await getDocs(sentQuery);

      // Get recent received transactions
      const receivedQuery = query(
        collection(db, 'hearts_transactions'),
        where('to_user', '==', userId),
        orderBy('created_at', 'desc'),
        limit(3)
      );
      const receivedSnapshot = await getDocs(receivedQuery);

      // Combine and sort
      const allTransactions = [
        ...sentSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })),
        ...receivedSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }))
      ] as HeartsTransaction[];

      allTransactions.sort((a, b) => b.created_at - a.created_at);
      setRecentTransactions(allTransactions.slice(0, 5));
    } catch (error) {
      console.error('Error loading transactions:', error);
    }
  }

  function formatDate(timestamp: number): string {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Nyss';
    if (diffMins < 60) return `${diffMins} min sedan`;
    if (diffHours < 24) return `${diffHours} tim sedan`;
    if (diffDays === 1) return 'Igår';
    if (diffDays < 7) return `${diffDays} dagar sedan`;
    
    return date.toLocaleDateString('sv-SE', { 
      day: 'numeric', 
      month: 'short'
    });
  }

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#2D5016" />
        <Text style={styles.loadingText}>Laddar profil...</Text>
      </View>
    );
  }

  const tips = reputation ? getReputationTips(reputation) : [];

  return (
    <ScrollView 
      style={styles.container}
      contentContainerStyle={{ paddingBottom: insets.bottom + 80 }}
    >
      {/* Profile Header */}
      <Card style={styles.headerCard}>
        <Card.Content>
          {editMode ? (
            <>
              {/* Riktigt namn */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Riktigt namn *</Text>
                <TextInput
                  value={editName}
                  onChangeText={setEditName}
                  mode="outlined"
                  style={styles.editInput}
                  autoCapitalize="words"
                  placeholder="Anna Svensson"
                  theme={{ colors: { background: '#fff' } }}
                />
                <Text style={styles.helperText}>
                  Detta namn sparas privat och visas bara efter kontakt
                </Text>
              </View>
              
              {/* Visningsnamn */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Visningsnamn</Text>
                <TextInput
                  value={editDisplayName}
                  onChangeText={setEditDisplayName}
                  mode="outlined"
                  style={styles.editInput}
                  placeholder="Anna S"
                  disabled={useAutoGenerated}
                  theme={{ colors: { background: '#fff' } }}
                />
                <View style={styles.checkboxRow}>
                  <Checkbox
                    status={useAutoGenerated ? 'checked' : 'unchecked'}
                    onPress={() => setUseAutoGenerated(!useAutoGenerated)}
                    color="#FFF"
                    uncheckedColor="#E0E0E0"
                  />
                  <Text style={styles.checkboxLabel}>
                    Generera automatiskt (t.ex. "Granne #1234")
                  </Text>
                </View>
                <Text style={styles.helperText}>
                  Detta namn visas för alla grannar innan kontakt
                </Text>
              </View>

              {/* Telefonnummer */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Telefonnummer (valfritt)</Text>
                <TextInput
                  value={editPhone}
                  onChangeText={setEditPhone}
                  mode="outlined"
                  style={styles.editInput}
                  keyboardType="phone-pad"
                  placeholder="+46701234567"
                  theme={{ colors: { background: '#fff' } }}
                />
                <Text style={styles.helperText}>
                  Delas bara efter godkänd kontaktförfrågan
                </Text>
              </View>

              {/* Edit Buttons */}
              <View style={styles.editButtons}>
                <Button
                  mode="outlined"
                  onPress={handleCancelEdit}
                  disabled={saving}
                  style={styles.editButton}
                  textColor="#FFF"
                >
                  Avbryt
                </Button>
                <Button
                  mode="contained"
                  onPress={handleSaveProfile}
                  loading={saving}
                  disabled={saving}
                  style={styles.editButton}
                  buttonColor="#FFF"
                  textColor="#2D5016"
                >
                  Spara
                </Button>
              </View>
            </>
          ) : (
            <>
              <Text style={styles.name}>{user?.name || 'Okänd användare'}</Text>
              {user?.display_name && (
                <Text style={styles.displayName}>
                  Visas som: {user.display_name}
                </Text>
              )}
              <Text style={styles.joinDate}>
                Medlem sedan {user?.created_at ? 
                  new Date(user.created_at).toLocaleDateString('sv-SE', {
                    year: 'numeric',
                    month: 'long'
                  }) : 'okänt'}
              </Text>
              <Button
                mode="text"
                onPress={() => setEditMode(true)}
                style={{ marginTop: 12 }}
                textColor="#FFF"
                icon="pencil"
              >
                Redigera profil
              </Button>
            </>
          )}
        </Card.Content>
      </Card>

      {/* Hearts Balance */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Ditt saldo</Text>
          <Text style={styles.heartsBalance}>
            🔥 {user?.hearts_balance || 0} Hearts
          </Text>
        </Card.Content>
      </Card>

      {/* Reputation - This shows detailed metrics, replaces Stats Grid */}
      {loadingReputation ? (
        <Card style={styles.card}>
          <Card.Content style={styles.loadingContent}>
            <ActivityIndicator size="small" color="#2D5016" />
            <Text style={styles.loadingText}>Laddar reputation...</Text>
          </Card.Content>
        </Card>
      ) : reputation ? (
        <>
          <ReputationCard reputation={reputation} showDetails={true} />
          
          {/* Improvement Tips */}
          {tips.length > 0 && (
            <Card style={styles.tipsCard}>
              <Card.Content>
                <Text style={styles.tipsTitle}>💡 Så förbättrar du din reputation</Text>
                {tips.map((tip, index) => (
                  <View key={index} style={styles.tipRow}>
                    <Text style={styles.tipBullet}>•</Text>
                    <Text style={styles.tipText}>{tip}</Text>
                  </View>
                ))}
              </Card.Content>
            </Card>
          )}
          
          {/* Refresh Button */}
          <Button
            mode="outlined"
            onPress={handleRefreshReputation}
            loading={refreshingReputation}
            disabled={refreshingReputation}
            style={styles.refreshButton}
            icon="refresh"
          >
            Uppdatera reputation
          </Button>
        </>
      ) : (
        <Card style={styles.card}>
          <Card.Content>
            <Text style={styles.noReputation}>
              Ingen reputation beräknad än. Börja hjälpa grannar för att bygga din reputation!
            </Text>
            <Button
              mode="contained"
              onPress={handleRefreshReputation}
              loading={refreshingReputation}
              disabled={refreshingReputation}
              style={styles.calculateButton}
              buttonColor="#2D5016"
            >
              Beräkna min reputation
            </Button>
          </Card.Content>
        </Card>
      )}

      {/* Recent Activity - Unique value, keep this! */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Senaste aktivitet</Text>
          
          {recentTransactions.length === 0 ? (
            <Text style={styles.emptyText}>Ingen aktivitet än</Text>
          ) : (
            recentTransactions.map((tx, index) => {
              const isSent = tx.from_user === auth.currentUser?.uid;
              return (
                <View key={tx.id}>
                  {index > 0 && <Divider style={styles.divider} />}
                  <View style={styles.transactionRow}>
                    <View style={styles.transactionInfo}>
                      <Text style={styles.transactionAmount}>
                        {isSent ? '-' : '+'}{tx.amount} Hearts
                      </Text>
                      <Text style={styles.transactionReason}>
                        {tx.reason || (isSent ? 'Hearts skickade' : 'Hearts mottagna')}
                      </Text>
                      <Text style={styles.transactionDate}>
                        {formatDate(tx.created_at)}
                      </Text>
                    </View>
                    <Text style={styles.transactionStatus}>
                      {tx.confirmed_by_receiver ? '✓' : '⏳'}
                    </Text>
                  </View>
                </View>
              );
            })
          )}
        </Card.Content>
      </Card>

      {/* Privacy Settings */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Sekretessinställningar</Text>
          
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingLabel}>Visa exakt avstånd</Text>
              <Text style={styles.settingDescription}>
                Om av: visar "Nära", "Inom 500m" etc. Om på: visar "247m"
              </Text>
            </View>
            <Switch
              value={exactDistance}
              onValueChange={async (value) => {
                setExactDistance(value);
                try {
                  const currentUser = auth.currentUser;
                  if (currentUser) {
                    await updateDoc(doc(db, 'users', currentUser.uid), {
                      'privacy_settings.exact_distance': value
                    });
                  }
                } catch (error) {
                  console.error('Error updating privacy settings:', error);
                  setExactDistance(!value); // Revert on error
                }
              }}
              color="#2D5016"
            />
          </View>
        </Card.Content>
      </Card>

      {/* Actions */}
      <Card style={styles.card}>
        <Card.Content>
          <Button 
            mode="outlined" 
            onPress={() => auth.signOut()}
            style={styles.logoutButton}
          >
            Logga ut
          </Button>
        </Card.Content>
      </Card>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F3F0',
    padding: 16
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F3F0'
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666'
  },
  loadingContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 12
  },
  headerCard: {
    marginBottom: 16,
    backgroundColor: '#2D5016'
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 4
  },
  displayName: {
    fontSize: 14,
    color: '#E0E0E0',
    marginTop: 4,
    marginBottom: 4
  },
  joinDate: {
    fontSize: 14,
    color: '#E0E0E0',
    opacity: 0.8
  },
  fieldContainer: {
    marginBottom: 20
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 8
  },
  editInput: {
    backgroundColor: '#fff'
  },
  editButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8
  },
  editButton: {
    flex: 1
  },
  helperText: {
    fontSize: 12,
    color: '#E0E0E0',
    marginTop: 4,
    fontStyle: 'italic',
    lineHeight: 16
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#FFF',
    marginLeft: 8,
    flex: 1
  },
  card: {
    marginBottom: 16
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 12
  },
  heartsBalance: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2D5016',
    textAlign: 'center',
    marginVertical: 8
  },
  noReputation: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20
  },
  calculateButton: {
    marginTop: 8
  },
  tipsCard: {
    marginBottom: 16,
    backgroundColor: '#E8F5E9'
  },
  tipsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 12
  },
  tipRow: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingRight: 8
  },
  tipBullet: {
    fontSize: 16,
    color: '#2D5016',
    marginRight: 8,
    marginTop: 2
  },
  tipText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    lineHeight: 20
  },
  refreshButton: {
    marginBottom: 16
  },
  emptyText: {
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
    paddingVertical: 20
  },
  transactionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8
  },
  transactionInfo: {
    flex: 1
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 2
  },
  transactionReason: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2
  },
  transactionDate: {
    fontSize: 12,
    color: '#999'
  },
  transactionStatus: {
    fontSize: 20
  },
  divider: {
    marginVertical: 8
  },
  logoutButton: {
    marginTop: 8
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16
  },
  settingInfo: {
    flex: 1,
    marginRight: 16
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 4
  },
  settingDescription: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16
  }
});
