import React, { useState, useEffect } from 'react';
import { Alert, View, ScrollView, StyleSheet } from 'react-native';
import { Text, TextInput, Card, Checkbox, Button, Divider, Switch } from 'react-native-paper';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { auth, db } from '../config/firebase';
import { doc, getDoc, collection, query, where, updateDoc, getDocs, orderBy, limit } from 'firebase/firestore';
import type { User, HeartsTransaction } from '../types';

export default function ProfileScreen({ navigation }: any) {
  const insets = useSafeAreaInsets();
  const [user, setUser] = useState<User | null>(null);
  const [stats, setStats] = useState({
    totalSent: 0,
    totalReceived: 0,
    resourcesPosted: 0,
    neighborsHelped: 0
  });
  const [recentTransactions, setRecentTransactions] = useState<HeartsTransaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [editMode, setEditMode] = useState(false);
  const [editName, setEditName] = useState('');
  const [editDisplayName, setEditDisplayName] = useState('');
  const [editPhone, setEditPhone] = useState('');
  const [saving, setSaving] = useState(false);
  const [useAutoGenerated, setUseAutoGenerated] = useState(false);
  const [exactDistance, setExactDistance] = useState(user?.privacy_settings?.exact_distance ?? false);

  useEffect(() => {
    loadProfile();
  }, []);

  async function loadProfile() {
    try {
      const currentUser = auth.currentUser;
      if (!currentUser) return;

      // Load user data
      const userDoc = await getDoc(doc(db, 'users', currentUser.uid));
      if (userDoc.exists()) {
        const userData = { id: userDoc.id, ...userDoc.data() } as User;
        setUser(userData);
        
        // Initialize edit values
        setEditName(userData.name || '');
        setEditDisplayName(userData.display_name || '');
        setEditPhone(userData.phone_number || '');
      }

      // Load stats
      await loadStats(currentUser.uid);
      
      // Load recent transactions
      await loadRecentTransactions(currentUser.uid);

      setLoading(false);
    } catch (error) {
      console.error('Error loading profile:', error);
      setLoading(false);
    }
  }

  async function handleSaveProfile() {
    // Validation
    if (!editName.trim()) {
      Alert.alert('Fel', 'Namn får inte vara tomt');
      return;
    }

    // Phone validation
    const phoneRegex = /^(\+46|0)[0-9]{9,10}$/;
    const cleanedPhone = editPhone.replace(/[\s-]/g, '');
    if (cleanedPhone && !phoneRegex.test(cleanedPhone)) {
      Alert.alert('Fel', 'Ogiltigt telefonnummer');
      return;
    }

    setSaving(true);
    try {
      const currentUser = auth.currentUser;
      if (!currentUser) return;

      // Determine display name based on checkbox
      let finalDisplayName;
      if (useAutoGenerated) {
        // Generate new random name
        finalDisplayName = `Granne #${Math.floor(1000 + Math.random() * 9000)}`;
      } else {
        // Use entered name, or keep existing, or generate if neither
        finalDisplayName = editDisplayName.trim() || 
          user?.display_name || 
          `Granne #${Math.floor(1000 + Math.random() * 9000)}`;
      }

      await updateDoc(doc(db, 'users', currentUser.uid), {
        name: editName.trim(),
        display_name: finalDisplayName,
        phone_number: cleanedPhone
      });

      // Reload profile
      await loadProfile();
      setEditMode(false);
      setUseAutoGenerated(false); // Reset checkbox
      
      Alert.alert('Sparat!', 'Din profil har uppdaterats.');
    } catch (error) {
      console.error('Error saving profile:', error);
      Alert.alert('Fel', 'Kunde inte spara profil');
    } finally {
      setSaving(false);
    }
  }

  function handleCancelEdit() {
    // Reset to current values
    setEditName(user?.name || '');
    setEditDisplayName(user?.display_name || '');
    setEditPhone(user?.phone_number || '');
    setUseAutoGenerated(false); // Reset checkbox
    setEditMode(false);
  }

  async function loadStats(userId: string) {
    try {
      // Count Hearts sent
      const sentQuery = query(
        collection(db, 'hearts_transactions'),
        where('from_user', '==', userId)
      );
      const sentSnapshot = await getDocs(sentQuery);
      const totalSent = sentSnapshot.docs.reduce((sum, doc) => {
        return sum + (doc.data().amount || 0);
      }, 0);

      // Count Hearts received
      const receivedQuery = query(
        collection(db, 'hearts_transactions'),
        where('to_user', '==', userId)
      );
      const receivedSnapshot = await getDocs(receivedQuery);
      const totalReceived = receivedSnapshot.docs.reduce((sum, doc) => {
        return sum + (doc.data().amount || 0);
      }, 0);

      // Count unique neighbors helped (received Hearts from)
      const uniqueNeighbors = new Set(
        receivedSnapshot.docs.map(doc => doc.data().from_user)
      );

      // Count resources posted
      const resourcesQuery = query(
        collection(db, 'resources'),
        where('user_id', '==', userId)
      );
      const resourcesSnapshot = await getDocs(resourcesQuery);

      setStats({
        totalSent,
        totalReceived,
        resourcesPosted: resourcesSnapshot.size,
        neighborsHelped: uniqueNeighbors.size
      });
    } catch (error) {
      console.error('Error loading stats:', error);
    }
  }

  async function loadRecentTransactions(userId: string) {
    try {
      // Get recent sent transactions
      const sentQuery = query(
        collection(db, 'hearts_transactions'),
        where('from_user', '==', userId),
        orderBy('created_at', 'desc'),
        limit(3)
      );
      const sentSnapshot = await getDocs(sentQuery);

      // Get recent received transactions
      const receivedQuery = query(
        collection(db, 'hearts_transactions'),
        where('to_user', '==', userId),
        orderBy('created_at', 'desc'),
        limit(3)
      );
      const receivedSnapshot = await getDocs(receivedQuery);

      // Combine and sort
      const allTransactions = [
        ...sentSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })),
        ...receivedSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }))
      ] as HeartsTransaction[];

      allTransactions.sort((a, b) => b.created_at - a.created_at);
      setRecentTransactions(allTransactions.slice(0, 5));
    } catch (error) {
      console.error('Error loading transactions:', error);
    }
  }

  function formatDate(timestamp: number): string {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Nyss';
    if (diffMins < 60) return `${diffMins} min sedan`;
    if (diffHours < 24) return `${diffHours} tim sedan`;
    if (diffDays === 1) return 'Igår';
    if (diffDays < 7) return `${diffDays} dagar sedan`;
    
    return date.toLocaleDateString('sv-SE', { 
      day: 'numeric', 
      month: 'short'
    });
  }

  if (loading) {
    return (
      <View style={styles.container}>
        <Text>Laddar profil...</Text>
      </View>
    );
  }

  return (
    <ScrollView 
      style={styles.container}
      contentContainerStyle={{ paddingBottom: insets.bottom + 80 }}
    >
      {/* Profile Header */}
      <Card style={styles.headerCard}>
        <Card.Content>
          {editMode ? (
            <>
              {/* Riktigt namn */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Riktigt namn *</Text>
                <TextInput
                  value={editName}
                  onChangeText={setEditName}
                  mode="outlined"
                  style={styles.editInput}
                  autoCapitalize="words"
                  placeholder="Anna Svensson"
                  theme={{ colors: { background: '#fff' } }}
                />
                <Text style={styles.helperText}>
                  Detta namn sparas privat och visas bara efter kontakt
                </Text>
              </View>
              
              {/* Visningsnamn */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Visningsnamn</Text>
                <TextInput
                  value={editDisplayName}
                  onChangeText={setEditDisplayName}
                  mode="outlined"
                  style={styles.editInput}
                  placeholder={user?.display_name || "Granne #XXXX"}
                  disabled={useAutoGenerated}
                  theme={{ colors: { background: '#fff' } }}
                />
                
                {/* Checkbox för auto-genererat */}
                <View style={styles.checkboxRow}>
                  <View style={styles.checkboxWrapper}>
                    <Checkbox
                      status={useAutoGenerated ? 'checked' : 'unchecked'}
                      onPress={() => {
                        const newValue = !useAutoGenerated;
                        setUseAutoGenerated(newValue);
                        if (newValue) {
                          setEditDisplayName(''); // Clear when checking
                        }
                      }}
                      color="#FFF" // White checkmark
                      uncheckedColor="#FFF" // White border when unchecked
                    />
                  </View>
                  <Text style={styles.checkboxLabel}>
                    Använd auto-genererat namn (Granne #XXXX)
                  </Text>
                </View>
                
                <Text style={styles.helperText}>
                  {useAutoGenerated 
                    ? 'Ett slumpmässigt namn kommer genereras vid sparning'
                    : user?.display_name 
                      ? `Lämna tomt för att behålla "${user.display_name}"`
                      : 'Lämna tomt för att behålla nuvarande namn'
                  }
                </Text>
              </View>
              
              {/* Telefonnummer */}
              <View style={styles.fieldContainer}>
                <Text style={styles.fieldLabel}>Telefonnummer</Text>
                <TextInput
                  value={editPhone}
                  onChangeText={setEditPhone}
                  mode="outlined"
                  style={styles.editInput}
                  keyboardType="phone-pad"
                  placeholder="070-555 12 34"
                  theme={{ colors: { background: '#fff' } }}
                />
                <Text style={styles.helperText}>
                  Format: 070-123 45 67 eller +46701234567
                </Text>
              </View>
              
              {/* Buttons */}
              <View style={styles.editButtons}>
                <Button
                  mode="outlined"
                  onPress={handleCancelEdit}
                  style={styles.editButton}
                  disabled={saving}
                  textColor="#FFF"
                  buttonColor="transparent"
                >
                  Avbryt
                </Button>
                <Button
                  mode="contained"
                  onPress={handleSaveProfile}
                  style={styles.editButton}
                  buttonColor="#6BCF7F"
                  textColor="#2D5016"
                  loading={saving}
                  disabled={saving}
                >
                  Spara
                </Button>
              </View>
            </>
          ) : (
            <>
              <Text style={styles.name}>{user?.name || 'Okänd användare'}</Text>
              {user?.display_name && (
                <Text style={styles.displayName}>
                  Visas som: {user.display_name}
                </Text>
              )}
              <Text style={styles.joinDate}>
                Medlem sedan {user?.created_at ? 
                  new Date(user.created_at).toLocaleDateString('sv-SE', {
                    year: 'numeric',
                    month: 'long'
                  }) : 'okänt'}
              </Text>
              
              <Button
                mode="outlined"
                onPress={() => setEditMode(true)}
                icon="pencil"
                style={{ marginTop: 12 }}
                textColor="#FFF"
                buttonColor="transparent"
              >
                Redigera profil
              </Button>
            </>
          )}
        </Card.Content>
      </Card>

      {/* Contact Requests */}
      <Card style={styles.card}>
        <Card.Content>
          <Button
            mode="outlined"
            onPress={() => navigation.navigate('ContactRequests')}
            icon="account-multiple"
            style={{ marginBottom: 12 }}
          >
            Kontaktförfrågningar
          </Button>
        </Card.Content>
      </Card>

      {/* Integrity Settings */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Integritetsinställningar</Text>
          
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingLabel}>Visa exakt avstånd</Text>
              <Text style={styles.settingDescription}>
                Tillåt godkända kontakter att se exakt avstånd istället för ungefärligt
              </Text>
            </View>
            <Switch
              value={exactDistance}
              onValueChange={async (value) => {
                setExactDistance(value);
                const currentUser = auth.currentUser;
                if (currentUser) {
                  await updateDoc(doc(db, 'users', currentUser.uid), {
                    'privacy_settings.exact_distance': value
                  });
                }
              }}
              color="#2D5016"
            />
          </View>
          <Divider style={{ marginVertical: 16 }} />
          
          <Button
            mode="outlined"
            onPress={() => navigation.navigate('BlockedUsers')}
            icon="account-cancel"
            style={{ marginTop: 8 }}
          >
            Blockerade användare
          </Button>
        </Card.Content>
      </Card>

      {/* Hearts Balance */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Ditt saldo</Text>
          <Text style={styles.heartsBalance}>
            🔥 {user?.hearts_balance || 0} Hearts
          </Text>
        </Card.Content>
      </Card>

      {/* Stats Grid */}
      <View style={styles.statsGrid}>
        <Card style={styles.statCard}>
          <Card.Content>
            <Text style={styles.statNumber}>{stats.totalSent}</Text>
            <Text style={styles.statLabel}>Hearts skickade</Text>
          </Card.Content>
        </Card>

        <Card style={styles.statCard}>
          <Card.Content>
            <Text style={styles.statNumber}>{stats.totalReceived}</Text>
            <Text style={styles.statLabel}>Hearts mottagna</Text>
          </Card.Content>
        </Card>

        <Card style={styles.statCard}>
          <Card.Content>
            <Text style={styles.statNumber}>{stats.resourcesPosted}</Text>
            <Text style={styles.statLabel}>Resurser postade</Text>
          </Card.Content>
        </Card>

        <Card style={styles.statCard}>
          <Card.Content>
            <Text style={styles.statNumber}>{stats.neighborsHelped}</Text>
            <Text style={styles.statLabel}>Grannar hjälpta</Text>
          </Card.Content>
        </Card>
      </View>

      {/* Recent Activity */}
      <Card style={styles.card}>
        <Card.Content>
          <Text style={styles.sectionTitle}>Senaste aktivitet</Text>
          
          {recentTransactions.length === 0 ? (
            <Text style={styles.emptyText}>Ingen aktivitet ännu</Text>
          ) : (
            recentTransactions.map((tx, index) => {
              const isSent = tx.from_user === auth.currentUser?.uid;
              return (
                <View key={tx.id}>
                  {index > 0 && <Divider style={styles.divider} />}
                  <View style={styles.transactionRow}>
                    <View style={styles.transactionInfo}>
                      <Text style={styles.transactionAmount}>
                        {isSent ? '-' : '+'}{tx.amount} Hearts
                      </Text>
                      <Text style={styles.transactionReason}>
                        {tx.reason || (isSent ? 'Hearts skickade' : 'Hearts mottagna')}
                      </Text>
                      <Text style={styles.transactionDate}>
                        {formatDate(tx.created_at)}
                      </Text>
                    </View>
                    <Text style={styles.transactionStatus}>
                      {tx.confirmed_by_receiver ? '✓' : '⏳'}
                    </Text>
                  </View>
                </View>
              );
            })
          )}
        </Card.Content>
      </Card>

      {/* Actions */}
      <Card style={styles.card}>
        <Card.Content>
          <Button 
            mode="outlined" 
            onPress={() => auth.signOut()}
            style={styles.logoutButton}
          >
            Logga ut
          </Button>
        </Card.Content>
      </Card>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F3F0',
    padding: 16
  },
  headerCard: {
    marginBottom: 16,
    backgroundColor: '#2D5016' // Dark green background
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF', // White text
    marginBottom: 4
  },
  displayName: {
    fontSize: 14,
    color: '#E0E0E0', // Light gray
    marginTop: 4,
    marginBottom: 4
  },
  joinDate: {
    fontSize: 14,
    color: '#E0E0E0', // Light gray
    opacity: 0.8
  },
  editLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2D5016',
    marginTop: 12,
    marginBottom: 4
  },
  fieldContainer: {
    marginBottom: 20
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF', // White text on dark background
    marginBottom: 8
  },
  editInput: {
    backgroundColor: '#fff'
  },
  editButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8
  },
  editButton: {
    flex: 1
  },
  helperText: {
    fontSize: 12,
    color: '#E0E0E0', // Light gray on dark background
    marginTop: 4,
    fontStyle: 'italic',
    lineHeight: 16
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4
  },
  checkboxWrapper: {
    backgroundColor: '#2D5016', // Match the header background
    borderRadius: 0,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center'
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#FFF',
    marginLeft: 8,
    flex: 1
  },
  card: {
    marginBottom: 16
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 12
  },
  heartsBalance: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2D5016',
    textAlign: 'center',
    marginVertical: 8
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#FFF'
  },
  statNumber: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2D5016',
    textAlign: 'center'
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    marginTop: 4
  },
  emptyText: {
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
    paddingVertical: 20
  },
  transactionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8
  },
  transactionInfo: {
    flex: 1
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 2
  },
  transactionReason: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2
  },
  transactionDate: {
    fontSize: 12,
    color: '#999'
  },
  transactionStatus: {
    fontSize: 20
  },
  divider: {
    marginVertical: 8
  },
  logoutButton: {
    marginTop: 8
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16
  },
  settingInfo: {
    flex: 1,
    marginRight: 16
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D5016',
    marginBottom: 4
  },
  settingDescription: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16
  }
});
